### ISSUE TITLE
Jenkins job failing

### ISSUE THREAD

**Issue by luntzel** [possibilities/g2j#1]
http://jenkins.versal.com/job/sync-gh-issues-to-jira/18376/console

Seems to bomb out because there are zero issues to sync. Please advise. Thanks in advance!

**Comment by luntzel** [comment]
That's probably not the issue, but I reckon you could figure that out.

**Comment by possibilities** [comment]
Ah, I see. I've disabled the job and posted an explanation on confluence, I'll send you the out of band since it won't be accessible to everyone who can see this.

Thanks Mark!
